import type { Metadata } from "next";
import { Inter, Geist_Mono, Oswald } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/layout/TopBar";
import HeaderPromo from "@/components/home/HeaderPromo";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bumper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} ${oswald.variable} antialiased`}
      >
        <div className="sticky top-0 z-50">
          <TopBar />
          <HeaderPromo />
        </div>
        {children}
      </body>
    </html>
  );
}
